---
name: CI

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  setup_release:
    name: Setup Release
    outputs:
      publish_release: ${{ steps.setup_release.outputs.publish_release }}
      release_body: ${{ steps.setup_release.outputs.release_body }}
      release_commit: ${{ steps.setup_release.outputs.release_commit }}
      release_generate_release_notes: ${{ steps.setup_release.outputs.release_generate_release_notes }}
      release_tag: ${{ steps.setup_release.outputs.release_tag }}
      release_version: ${{ steps.setup_release.outputs.release_version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Release
        id: setup_release
        uses: LizardByte/setup-release-action@v2024.717.220227
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs:
      - setup_release
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: Plugger.bundle

      - name: Set up Python
        uses: LizardByte/setup-python-action@v2024.609.5111
        with:
          python-version: '2.7'

      - name: Set up Python Dependencies
        shell: bash
        working-directory: Plugger.bundle
        run: |
          echo "Installing Requirements"
          python --version
          python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade pip setuptools wheel

          # install dev requirements
          python -m pip install --upgrade -r requirements-dev.txt

          python -m pip install --upgrade --target=./Contents/Libraries/Shared -r \
            requirements.txt --no-warn-script-location

      - name: Compile Locale Translations
        working-directory: Plugger.bundle
        run: |
          python ./scripts/_locale.py --compile

      - name: Install npm packages
        working-directory: Plugger.bundle
        run: |
          npm install
          mv ./node_modules ./Contents/Resources/web

      - name: Build plist
        shell: bash
        working-directory: Plugger.bundle
        env:
          BUILD_VERSION: ${{ needs.setup_release.outputs.release_tag }}
        run: |
          python ./scripts/build_plist.py

      - name: Package Release
        shell: bash
        run: |
          7z \
            "-xr!*.git*" \
            "-xr!*.pyc" \
            "-xr!__pycache__" \
            "-xr!plexhints*" \
            "-xr!Plugger.bundle/.*" \
            "-xr!Plugger.bundle/cache.sqlite" \
            "-xr!Plugger.bundle/codecov.yml" \
            "-xr!Plugger.bundle/crowdin.yml" \
            "-xr!Plugger.bundle/DOCKER_README.md" \
            "-xr!Plugger.bundle/Dockerfile" \
            "-xr!Plugger.bundle/docs" \
            "-xr!Plugger.bundle/scripts" \
            "-xr!Plugger.bundle/tests" \
            a "./Plugger.bundle.zip" "Plugger.bundle"

          mkdir artifacts
          mv ./Plugger.bundle.zip ./artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Plugger.bundle
          if-no-files-found: error  # 'warn' or 'ignore' are also available, defaults to `warn`
          path: |
            ${{ github.workspace }}/artifacts

      - name: Create/Update GitHub Release
        if: ${{ needs.setup_release.outputs.publish_release == 'true' }}
        uses: LizardByte/create-release-action@v2024.614.221009
        with:
          allowUpdates: true
          body: ${{ needs.setup_release.outputs.release_body }}
          discussionCategory: announcements
          generateReleaseNotes: ${{ needs.setup_release.outputs.release_generate_release_notes }}
          name: ${{ needs.setup_release.outputs.release_tag }}
          prerelease: true
          tag: ${{ needs.setup_release.outputs.release_tag }}
          token: ${{ secrets.GH_BOT_TOKEN }}

  pytest:
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: Plugger.bundle

      - name: Extract artifacts zip
        shell: bash
        run: |
          # extract zip
          7z x Plugger.bundle.zip -o.

          # move all files from "Plugger.bundle" to root, with no target directory
          cp -r ./Plugger.bundle/. .

          # remove zip
          rm Plugger.bundle.zip

      - name: Set up Python
        uses: LizardByte/setup-python-action@v2024.609.5111
        with:
          python-version: '2.7'

      - name: Install python dependencies
        shell: bash
        run: |
          python -m pip --no-python-version-warning --disable-pip-version-check install --upgrade \
            pip setuptools wheel
          python -m pip --no-python-version-warning --disable-pip-version-check install --no-build-isolation \
            -r requirements-dev.txt

      - name: Test with pytest
        id: test
        shell: bash
        run: |
          python -m pytest \
            -rxXs \
            --tb=native \
            --verbose \
            --color=yes \
            --cov=Contents/Code \
            tests

      - name: Upload coverage
        # any except canceled or skipped
        if: >-
          always() &&
          (steps.test.outcome == 'success' || steps.test.outcome == 'failure') &&
          startsWith(github.repository, 'LizardByte/')
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          flags: ${{ runner.os }}
          token: ${{ secrets.CODECOV_TOKEN }}
